### ISSUE TITLE
Real World Sample Application

### ISSUE THREAD

**Issue by electricjones** [spider/spider#115]
So, I am searching for a new job and have had some positive leads. Whatever the case, I would be able to work less hours and devote more time to things like this. I really want to get Spider to a usable form (0.4) soon. There isn't that much more to do, I don't think.

Anyway, onto this PR. I think it would be beneficial to consider hacking together a sample application that uses Spider. This would be something that is useful in its own right, contain lots of examples of how to integrate Spider into a codebase, and be a great testing mechanism for us to make sure things work beyond our automated tests (real world testing is always important).

It's not a super high priority, and I'd like to keep things pretty simple. I just wanted to throw the idea out there and see if anyone had any ideas. What php general use application would benefit from graph databases? A micro social network? Some data-analysis package? An innovative wiki? I'm really up for anything. @smolinari this may be something you could help contribute to if you don't feel terribly comfortable with the core.

Just thinking out loud. I'm going to dive back into spider next week.

**Comment by smolinari** [comment]
Thanks for considering me. I am not even close to the point where I need to implement Spider, but I'd like to take a jab at using it for a PoC. It would be a good learning experience too. I'd be using ODB as the backend, since I know the most about it. 

I'd like to build a proof on concept for a particular discussion engine. 

The problem. Discussions are really bad, when they can't "thread out". Good examples are the comment sections in Facebook or any other "social network". The first attempts to make discussions "threaded" where the old UBB forums, where threads where "subthreaded" and you'd have a tree view of the discussion. Though the clicking through the discussion was a pain in the butt. 

The newer, more accepted form of threaded discussion uses quoting and a more linear view of the posts, either with infinite scrolling or pagination. However, the quoting causes a lot of replication of text and the discussions don't really thread well that way too. 

Sites like Slack or Gitter have a chat like functionality, but absolutely no threading. As soon as a few discussions are happening, then the "chat" becomes a really big mess. Slack has the ability to split up a channel into subchannels, but that really isn't threaded discussions either. That is just a categorization.

The solution. Something along the lines of how Google Wave's discussions work.

https://www.youtube.com/watch?v=xBzuuWZPaXc

Or sort of like Rizzoma's discussions - https://rizzoma.com/

The PoC would naturally be very simple, but getting a threaded discussion working through a graph database would be a dream.

Scott

**Comment by electricjones** [comment]
Interesting idea. Let's keep chewing on it and drafting some things out. I like the direction, personally.

I would offer a couple thoughts.

1.) Make heavy use of composer packages and probably a micro-framework like Lumen, Slim, or Silex. No need to create all those components and it would make testing Spider more viable if we could be sure to have the rest of the system supported.

2.) Spider won't really be ready for something like this for a few weeks (hopefully), just keep that in mind.

3.) You say you use Orient, which is fine, but the point of Spider is that any of the supported DBs would work identically (with supported features) through Spider. So, we would want to have a basic graph setup which can be loaded into each of the databases and let the user (through a config value) decide which db to use.

**Comment by smolinari** [comment]
To 3). Ok. I guess I have spider-box to help me out too. :smile: 

To the rest. Sounds good. Though, what did you mean by this?

> it would make testing Spider more viable if we could be sure to have the rest of the system supported.

Which rest of the system?

Scott

**Comment by electricjones** [comment]
The real world application. For instance, if we build the discussion thing, that also includes Authroization, Web Requests, Templating, etc, etc. The "framework level" code. I am saying it may be best to use established code for all this (like a microframework and composer packages) so the only code we are creating/testing is the application logic itself and Spider.

And, yes, spider-box would be perfect for something like this :smile_cat:

**Comment by smolinari** [comment]
Hey Chris. Hope all is well with you? 

March is practically empty on my projects list. I'd like to start on this. How are things with you and getting more done on Spider?

Scott

**Comment by smolinari** [comment]
Hey Chris, @chrismichaels84 

How are things going? I will be on vacation in May. I could start some serious work on both spider or this idea. I just need to know where to attack. 

Scott

**Comment by electricjones** [comment]
That is great. Sorry. I've started a new job and haven't had time to get to this. But, I think I am going to be able to devote most of my tommorrow to cleaning up spider. Maybe we can chat about direction? I believe you have my email address so we can setup a slack or something.

**Comment by smolinari** [comment]
How about a Gitter channel/room? https://gitter.im

Scott

**Comment by electricjones** [comment]
Works for me. Anytime tomorrow or next week best?

**Comment by smolinari** [comment]
I am online tomorrow evening around 19:30 CET, which is 13:30 EST.

Scott

**Comment by electricjones** [comment]
This issue was moved to spider/orb#1
