### ISSUE TITLE
Heads up on driver handling and query building

### ISSUE THREAD

**Issue by dmill-bz** [spider/spider#3]
Hey,

I've been keeping an eye on this and thought I'd point out a little something that might need to change down the road. 

Ultimately your driver option will also influence how your query is built (ie: which language  the resulting script will be in) 
This can become a little tricky considering there are often multiple options. For example Neo4j can either receive queries in `gremlin` or in `cypher`. This will be even more obvious using the rexster server for TP3 (gremlin-server) because you'll be able to submit either one as well. 
Right now your interface doesn't allow customizing which language you chose (only submitting it as an option for the driver I guess?).

Also, building scripts for `cypher`, `orientDB SQL`, `SPARQL` and variations are going to be very similar to how the php PDO currently works because these are all declarative languages. However `gremlin` is an imperative language so the queries will have to be constructed in a completely different manner. I'm not sure it's possible at all to offer one common query building interface across all systems. 

Just thought it might be worth considering/discussing.

**Comment by electricjones** [comment]
Wow, I appreciate your thoughts and keeping an eye on this repo. To be honest, at this point this project is as much an experiment and learning tool as eventually useful tool. We use OrientDB at [Phoenix Labs](http://phoenixlabstech.org) and I have become interested in graph technology.

I had considered the Query Builder problem, and had an idea about a solution. I had intended to create an interface (or set of interfaces) for query building. So an `Orient`, `Cypher`, `SPARQL`, etc builder could implement the same interface. Then, the query is built using the `Builder` which pops out a `Query` object with a simple `getQuery()` method. You could also create a `Query` object directly from your own query. That object is then handed to the driver which executes the query in the native language.

I had intended to create a first-party `GremlinQueryBuilder` that would act as a default of sorts for driver makers, so they would not necessarily have to create a QueryBuilder for Tinkerpop compatible systems.

Ultimately, the end-user could choose to use the driver directly and inject the `QueryBuilder` or `Query` manually, but the goal of the project is to abstract that away to a OGM, and even further to a top-level `Spider` object that also has utilities and some other bells and whistles, including the ability to create graph data without any persistence or to persist a static graph in any manner.

I hadn't considered that Gremlin was imperative and the rest are declarative. My next step was to hack together a basic driver for Neo4j and Rexster (really just wrapping existing drivers like yours).

The ultimate goal is to create a fluent, predictable, top-level api for working with graph-data that abstracts away the particular graph implementation. So, you could use multiple, switch bases relatively easily, or even (in theory) use MySQL with the right driver.

Do you have any suggestions about the QueryBuilder issue to reach that top goal?

Thanks again.

**Comment by dmill-bz** [comment]
It might be a little tricky. 
Mutating the graph should not be an issue. Your active records will provide all the necessary methods and users probably won't have to even worry about the underlying queries. 

Traversal operations on the other hand can be tricky. I think the top goal is absolutely attainable for the declarative languages as they work on a per block basis (`WHERE` block, `SELECT`, `LIMIT/FILTER`, etc..). You should just take one of them as a basis (probably cypher) and replicate traditional query builder behavior such as : http://www.yiiframework.com/doc-2.0/guide-db-query-builder.html .
You can then override the query building classes for each query language.

The tricky part is gremlin. To use gremlin with that `QueryBuilder`, it would have to convert your request into gremlin... That's kind of reinventing the wheel in the sense that all the declarative languages already do `cypher` > `java` or `orientSQL` > `java`. You would have to do `QueryBuilder` > `java` (gremlin is essentially java). I've read about some people wanting to do this conversion but I haven't seen any source code for this so I don't know what the downfalls are other than it being a lot of work. 

Providing a `GremlinQueryBuilder` as a fill in for people who really want to use gremlin could be an option. It's use would be completely different from `QueryBuilder` but that's not outrageous in itself. For example:

``` php
$query = new GremlinQueryBuilder;
$query->graph()->V(152)->out('FRIEND')->has('age', 30);
$script = $query->getScript(); // g.V(152).out('FRIEND').has('age', 30);
```

You will however run into issues with some features though. Such a feature could be defining scopes. For example (pseudo code):

``` php
$user = User::getFromDb('john.m@gmail.com'); //lets pretend this returns a user object
$query = new QueryBuilder; // create a new **non-gremlin** builder
$query->select("*");
$query->label('user');
$query->where("type == 'user'");
$query->andWhere(QueryBuilder::link(['OUT', ['FRIEND'])->where('name == "marko"'));

if($user->isAdmin)
{
    $query->andWhere("type == 'admin'");
}

$script = $query->getScript();
/**
 * We get all the users that are friends with marko.
 * If john is an admin we get all users and admins that are friends with marko
 */
```

This works with a QueryBuilder. But how do you affect a GremlinQueryBuilder to change it's traversal from 
`g.V().has(label, 'user').has('type', 'user').and(out('FRIEND').has('name', 'marko'))`
to
`g.V().has(label, 'user').has('type', within, ['user', 'admin']).and(out('FRIEND').has('name', 'marko'))`
That's actually a tough one to solve. 

Food for thought

**Comment by dmill-bz** [comment]
Hey I'm using this as a discussion. Noticed another point in your recent changes I wanted to bring up. At least it's worth thinking about.

The following is on the basis of users being able to configure scopes. A scope being a query or partial query that filters the result set and is used regularly enough that it would make sense to separate it in order to unit test it and reuse it at will.
We could imagine the following scopes:

``` php
$postQuery->onlyPublished(); // or Post::find()->onlyPublished()->all()
$postQuery->onlyHot();
$userQuery->onlyActive(); // or User::find()->onlyActive()->all()
$userQuery->onlyBlocked();
$userQuery->onlyPopular();
// etc..
```

The problem with setting the return method like you do is that the type of query will probably be defined by the ActiveRecord you used to initiate the query (the start object if you will) when usually the scopes you want to apply belong to the return object.

Here's such an example in pseudo-code

``` php
Post::find([
   /* start from a set of posts, get authors and set return object as \something\User */
])->onlyActive()->all();
```

This will fail because `onlyActive()` is a `User` scope. Really what you would want is:

``` php
User::find([
   /* start from a set of posts, get authors */
])->onlyActive()->all();
```

But this implies passing a starting object of `Post` to the query.

I don't know if you see what I mean.

**Comment by electricjones** [comment]
That is an interesting concern that I hadn't considered. The problem I was running into was that each driver ultimately returns (sometimes wildly) different result objects with different methods which can make it difficult to rely on using such an object when and if you use multiple drivers or swap one for another (say for different environments).

Truthfully, I've shelved the query building issue until I've done some more research on the declarative/imperative issue. However, in order to save myself refactoring, would it be better to move the bit that conforms the return object to user specification somewhere else? My goal was to have it at the last point before the user touches the result. The connection may not be the best place to do that.

I really appreciate your thoughts.

**Comment by dmill-bz** [comment]
Oh sorry, I noticed I miss-read the point of your return object. So my previous post is moot (though good to keep in mind)

I think SpiderGraph should be consistent in how responses are returned from the driver. How about the process bellow:

```
                            Connection     
[Driver Layer ----> mixed response ---> SpiderGraph response] ---> [Object Layer] and/or [Application layer]
```

Provided the above, each driver response would be returned from Connection as an object. Lets just call it `SpiderGraphResponse`. This object already serves abstraction from the drivers. And if anyone absolutely needs the raw data from the driver (to use with an existing library they have) they could always use `SpiderGraphResponse::getNative()` or something similar (native might be a little confusing with meaning a php native but you get the idea).

There wouldn't be any need for a return type in this scenario. And without being entirely knowledgeable about various objects and methods returned by the drivers out there, I think there should be a separation between response and querying logic. That is to say that doing things this way probably won't result in  missing out on important functionalities provided by some drivers. 

This is just me thinking out loud

**Comment by electricjones** [comment]
That is moreless the way its setup now. Any call to the connection (say `getVertex()`) is just shunted down to the driver which sends back a response to the connection. 

The connection then conforms that response based on configuration: `Graph` by default, `WhateverTheyWant` if specified in configuration, or the raw response if specified `'native'`. 

I will definitely have to revise the documentation, and, now that I think about it, "native" isn't the right word.

Though in all things, I love simplicity -- especially in the api. Do you think it would be best to eliminate the `WhateverTheyWant` option, and configurable return objects all together. Simply send them a `Graph` with a `::getRaw()` method? If the user wants to map it to their own custom response, that's their business.

**Comment by dmill-bz** [comment]
Yes I definitely think that would be the best option.

**Comment by electricjones** [comment]
I would appreciate your thoughts on this implementation:

Any transaction, query, or command will eventually go through the `Connection` which holds the specific driver for the datastore. This is true whether they use the upcoming Models, direct call, or whatever else.

All drivers implement a `DriverInterface` which includes various `mapToXResponse` methods.

The `Connection` class uses the driver's `mapTo` methods to conform any raw response into a predictable response, with a `::getRaw()` method.

To my mind, there are four kinds of responses any driver can send, depending on the transaction:
1. A `Graph` holds several vertices and edges in relation (likely in a GraphSON like representation)
2. A `Vertex`
3. An `Edge` (in the case of creating or deleting just one edge)
4. and a primitive value (`bool`, `int`, etc) if only one value was retrieved.

To my mind, the first three deserve their own PHP classes, each likely extending a base `Record` class for type hinting and shared methods.This Record class would also extend my data-manager class for simple container functionality (array dot notation, etc).

My question is: should all these responses, regardless of which they are, be wrapped in a general `SpiderResonse` which would be little more than a type hinting tool? I feel like wrapping all these responses inside other responses is adding needless performance overhead.

That said, it would also be thinkable for the connection to send back a single `SpiderResponse` and forget the above four types of responses all together, though this seems clumsy to me.

Thanks for your thoughts.

**Comment by dmill-bz** [comment]
I started writing a more complete post but just wanted to run something by you before providing a more thorough opinion. 

You say that `Driver` would provide a number of `mapToX` methods. Can you provide a few usage examples?
I feel like `Driver` should do the normalizing and not `Connection`. In essence, that `Driver` should return a `SpiderResponse` but I might be missing the advantage of `mapTo`.

**Comment by dmill-bz** [comment]
Also looking at your code it looks like the `DriverInterface` facilitates creating and removing vertices. Somehow this feels like it should be on the `Record` or `Query` level. I think the `Driver` should simply shove queries down to the server. But maybe there's an issue there with REST based drivers? I'm not sure.

**Comment by electricjones** [comment]
I've pushed my commits for the basic idea to the develop branch, so you can see my ideas in [`Connection`](https://github.com/chrismichaels84/Spider-Graph/blob/develop/src/Connections/Connection.php) and the driver implementation [OrientDriver](https://github.com/chrismichaels84/Spider-Graph/blob/develop/src/Drivers/OrientDB/OrientDriver.php).

Basically, the Driver IS sending the response, its just the connection that is deciding when the driver is ready to respond.
1. The user calls `$connection->addVertex($properties)`
2. The `Connection`, using magic methods, passes the call down to the driver

``` php
$response = call_user_func_array([$this->driver, $name], $args);
```
1. The driver does whatever it does, and passes its _raw response_ to the `__call()` method on the `$connection`
2. The `$connection` then passes the response through the driver's `mapToReturnObject()` or `mapToResponse()` or whatever.
3. The `$connection` returns this response to the user.

The reason for the extra step is so the driver can use its own methods when building the initial response, while still dealing with its native response object. Only after the entire process is finished and the driver is ready to send it back to the user, does the connection use the driver's helper method to force a SpiderResponse.

The extra step also allows the connection to determine what _kind_ of response it is (primitive value, Graph, Record, or Collection), and could potentially pass the response through a dedicated `mapToXResponse()` method for each type. Though this would probably be better handled in the driver's helper method since it will know how to interpret the response.

The real benefit is that the `Connection` has access to configuration properties set by the user, so can pass the response through the correct helper method based on a config value. So if the user has configuration set to `raw_response`, then the connection could just fire back the raw response with no more performance overhead. I don't know if this is worth the extra option, but I was trying to keep future options open. Who knows what configurable options my land in the future that would be able to make use of this workflow.

Does that make sense?

**Comment by electricjones** [comment]
I was moreless copying the functionality of a couple vendor-specific drivers I found and they all included that functionality. It is more performant to use the direct command than to process a query, or so they say. I can't imagine using anything but queries and a builder myself.

**Comment by dmill-bz** [comment]
I see! I had a look at your implementation of the orientDb driver and it makes sense. The thing is, Drivers such as the gremlin-server one don't have any of those methods. Some can be implemented but that would require writing the queries without a query builder and that just doesn't feel right. 

I was going to have a quick look at implementing gremlin-php driver for TP3 but I wouldn't know where to start. `gremlin-server` just takes queries, and that's it. And even then some things like creating/removing a database aren't possible.

I think part of the issue is that since there was no ORM/OGM available and no real architecture around graph data modeling in php, the drivers ended up doing more than just driver work, implementing all these extra methods to provide an easy to use API

The headache here is that I'm not sure how you reconcile both. Maybe if `Connection`, `Driver`, and `Query` are all database specific?

It might be interesting checking what the direct commands do differently from issuing a query.

**Comment by electricjones** [comment]
I would agree, and would lean toward just using queries, mostly because it would encourage more drivers if the are easier to create. The issue comes in schema operations, because each implementation I've seen takes a radically different approach to schema or schema-less-ness (if I can make up that word, lol).

Though, I guess (forgoing the schema problem), you can do everything else through queries. It may be best to simplify the `DriverInterface` to just query-based operations and pass the problem along to the `QueryBuilder`. I hadn't thought about the individual operations being there for historical reasons, and that isn't a good enough reason for me.

The real problem I have (at least with orient) is that (using the binary or http protocol), you send read-only and write commands differently. So, you can't just send all queries the same way. The driver would have to know how to handle this, I suppose. 

Or, have two methods on the driver: `query()` for read only, idempotent scripts, and `command()` for write, non-idempotent scripts. In other systems, the driver could just alias both of these.

And, for now, I want to shelve the schema issue. All these systems have excellent web-based management systems to create schema.

I want to focus on the drivers, connections, models, and querybuilders. All of which I am laying to groundwork for. I am still not sure how to handle gremlin-query-builder.

**Comment by dmill-bz** [comment]
I agree with you.

I also think it would make sense down the road to provide separate `Schema` classes for each Driver or in the case of gremlin-php driver for each database (since TP3 doesn't handle schema directly but through vendor APIs). 

Maybe `DriverInterface` could have the following public methods:
- `open()`
- `executeCommand()`
- `run()` ? (would exit without checking for a response)
- `startTransaction()`
- `stopTransaction()`

What's left is the read/write issue you brought up. Either `executeCommand()` can separate reads from writes, or we have to implement a set of `executeReadCommand` and `executeWriteCommand`

As far as gremlin-query-builder goes. I think it makes sense to leave that one for later. Better to concentrate on the declarative languages first. Orient and Neo4j are quite popular within the PHP world. Those would be a good start. Furthermore, gremlin now provides methods for graph specific languages so you could use gremlin-server with `cypher` queries if using a neo4j graph.

**Comment by electricjones** [comment]
I have released the next draft version to include these thoughts

**Comment by dmill-bz** [comment]
Think we should close this at this point. Most of the discussion at this stage is in other issues.
