### ISSUE TITLE
Support sessions

### ISSUE THREAD

**Issue by electricjones** [spider/spider#31]
We can add sessions too. I'm kind of torn when it comes to it.

On one end it's part of the Driver::$client APIs and it should bubble up to Spider. On the other it's slow, somewhat more ressource intensive for the servers and overall a feature that isn't all that useful outside of transactional scenarios (that usually require it).

This issue is to judge interest in sessions support. Spider will eventually support it, but it's not very high on our list right now. Just collecting thoughts here

Driver::$client should enable sessions automatically on TRANSACTION START or if they don't Spider definitely should. I'm not sure how useful a feature it is outside of that scenario though.

There's certainly no harm in providing the API for it. It's just a matter of writing the code and the proper test scenarios (combination of session/no-session transaction/no-transaction) which might not be as high a priority as SSL support.

I'll have to check how sessions work with Neo4J as well.

**Comment by smolinari** [comment]
As I mentioned in the other thread about SSL, I believe concurrent connectivity over sessions is needed to allow for parallelization of work. This thread also holds an interesting discussion about the needs, wants and implementation for session functionality.

https://github.com/orientechnologies/orientdb/issues/2229

Scott

---

On the point of SSL, I'd consider it a must. Any application should be as secure as it can be. I can't imagine SSL implementation would need to be above the driver level either. So, at most, a configuration setting to turn it on, which should be the default. 

On the point of sessions, doesn't the use of sessions allow for concurrent connections to be used for parallelization of work? If true, it is more a performance feature than anything else.  Still, good performance is always good to have, almost a must, but can be brought in a later point, when Spider is stable. Just need to keep them in mind for later, as parallelization of work isn't something common in PHP anyway. 

Btw, the other bleading edge PHP technology I am looking at and learning is [Appserver.io](http://appserver.io/). It most definitely allows for parallelization of work, even with PHP. :wink:  

Scott

**Comment by dmill-bz** [comment]
Thanks for the feedback Scott. This is a little tricky.

Technically sessions aren't required for parallelization of work, nor are they required for concurrent work (subtle difference). If anything, seeing as sessions hold onto variable assignments, concurrent tasks in a single session could lead to disastrous conflicts.

The link you posted suggested using sessions as a means of cutting down unnecessary authentication overhead which is already a different issue (specific to Orient) but also not a good way of going about it in the first place (and not the way they ended up implemented it).

We should look at it like this: 
- session-less requests have an immediate expiry. Variables and Binds are set by the request/request-script and then immediately garbage collected once the response is returned. If transactions are being used, session-less requests will start and then commit/rollback the transaction with every query.
- session enabled requests expire after they time-out or are manually closed. Variables and Binds are set by the request/request-script and are kept until the session closes. Meaning that they are accessible to any other query run within the scope of that session. This scenario's most useful user case is when using transactions, you'll want to mutate the graph in multiple queries and keep the option of rolling them all back, or committing them all together. 

`Driver::$client` with transaction support will almost always create a session in the background for the transaction so we don't need to implement sessions in Spider for this use case.

Any multi-thread scenarios I can think of can be accomplished without sessions so long as Spider provides transaction fail-retry strategies which will be a requirement for production anyways because of possible concurrent writes. 

Of course I'm not saying we shouldn't implement sessions. We most definitely should. It just isn't a priority.

**Comment by dmill-bz** [comment]
To add to this, single read operations should always be session-less.
Normally write operations should always be transactional and within a session (this include read operations that expect to get mutated information before the transaction is committed).

**Comment by smolinari** [comment]
I agree, session functionality isn't a priority. 

I thought I read somewhere in that (or some) thread that sharing of the session among clients (different application servers) would be necessary for parallelization of work among those clients/ servers. Maybe I misunderstood it too? 

Scott

**Comment by dmill-bz** [comment]
No, you are correct that does make sense with eventually consistent storage backends for example, where writes may not be propagated through the cluster uniformly (fast enough) for a subsequent read to see mutations. In that case you would want to do everything in a session. Lets keep this in mind. 

_Though there still is no guaranty that your read will execute after the write is done in an asynchronous environment._
