### ISSUE TITLE
Specify dependency versions

### ISSUE THREAD

**Issue by electricjones** [spider/spider#91]
I've noticed that you switched to CamelCase for brightzone. @PommeVerte, can you update the gremlin driver to match? Please update the `master` branch and we can merge the change into the other branches and release 0.3.2.

**Comment by dmill-bz** [comment]
Yeah I forgot to mention not to upgrade the driver just yet as I wanted to make that change first. I've got a couple of things to sort out and then I'll tackle this :)

**Comment by dmill-bz** [comment]
On a side note there's no real benefit to upgrading until gremlin-server 3.0.2 releases

**Comment by dmill-bz** [comment]
We should actually change the composer.json file to load v1.0 (and avoid 2.0.0 BC breaking changes for the moment). Should I just go ahead and to that on master?

**Comment by electricjones** [comment]
Yes, please. We should really make all dependencies version specific.

**Comment by dmill-bz** [comment]
ok lets make this issue about that. It should be easy enough since the tests pass we should just put the versions found in the .lock

**Comment by electricjones** [comment]
When specifying versions, I like to leave the security release as a wildcard, and trust that the maintainers don't introduce breaking changes into security releases. 

It seems like (in the master branch) the dependencies not specified are (with the latest releases):
`everyman/neo4jphp` -> `0.1.*`
`satooshi/php-coveralls` -> `0.6.*`
`codeception/specify` -> `0.4.*`

While we're at it, let's update PHP to `5.6` per #83, but only in develop and beyond. I don't think anyone is using the current release, but I'd rather not destroy something for no reason :)

Objections? Thoughts?

**Comment by dmill-bz** [comment]
Yes I like that. We can also try and see if any of those libraries follow a specific standard which would allow us to be more specific with our wildcards. I know that with gremlin-php I follow [semantic versioning](http://semver.org/) so as long as you stick to a major version there shouldn't be any BC breaking changes (e.g. `1.*`, `2.*` etc.).

The recent failures in tests were due to composer bumping us up to `2.0.0`

Obviously anything bellow version `1` is probably going to change so I think your versions above are as correct as can be.

**Comment by electricjones** [comment]
This has been finished, yes?

**Comment by dmill-bz** [comment]
yes
